apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: jsl4twnjw-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:7f5b081542787be754d9b6019c66ffcdae8848a4@sha256:b51d15c77b6a3070442bdf4c022544cbf1dcd259979d06d8e2c1fddb83f6151f
          name: container-image
