apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: jsl4twnjw-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/jsl4twnjw-dotnet-basic-gitops